### ISSUE TITLE
Dependency on arrow-format 0.4 limits tonic and prost to respectively versions 0.6 and 0.9.

### ISSUE THREAD

**Issue by GPSnoopy** [jorgecarleitao/arrow2#1010]
Crate `arrow2` version 0.11 cannot be used with the `io_flight` feature if the application uses a newer version of `tonic` or `prost`.

I have opened a PR against `arrow-format` but the repository looks stale since October 2021: https://github.com/DataEngineeringLabs/arrow-format/pull/4

**Comment by jorgecarleitao** [comment]
It is not stalled, it just does not need much updates. Maybe we should setup the dependabot there so we know when dependencies get bumped

**Comment by jorgecarleitao** [comment]
Thanks for the report! 

PR with the bump on our side: https://github.com/jorgecarleitao/arrow2/pull/1011

**Comment by GPSnoopy** [comment]
Hi @jorgecarleitao, thanks for the details and the extra PR. Your open source efforts are much appreciated. 😃
