### ISSUE TITLE
"Arrow file does not contain correct header" from Arrow2 but reads with Rust Arrow

### ISSUE THREAD

**Issue by joshuataylor** [jorgecarleitao/arrow2#1031]
Hi!

It's amazing to see the work this crate has done, when I first checked it out it was super early days but made my last project so much faster and easier to work with.

For that reason, I want to use it with [req_snowflake](https://github.com/joshuataylor/req_snowflake) , which will be an Elixir Snowflake Connector. Right now we only read their JSON response but we also want to support Snowflakes Arrow response, which should hopefully be pretty straight forward using Rust + NIFs (the way to communicate with Rust libraries from Elixir/Erlang).

I'm having a problem reading a file though, I've got a repo here: https://github.com/joshuataylor/req_snowflake

Mind the messy code, was just trying to get it down to a quick reproduction (find the `example_snowflake_data` file above, it's from the sample snowflake data from `select * from snowflake_sample_data.tpch_sf1.lineitem`):

1/ Arrow2:
```
    let mut file = File::open("example_snowflake_data").unwrap();

    // Try and read metadata
    let _metadata = read_file_metadata(&mut file).unwrap();
```

2/ Arrow (to also show it can write the result properly):
```
    let file = File::open("example_snowflake_data").unwrap();

    let reader = StreamReader::try_new(file, None).unwrap();
    let buf = Vec::new();
    let mut writer = LineDelimitedWriter::new(buf);

    reader.for_each(|batch| {
        let batch = batch.unwrap();
        writer.write_batches(&[batch]).unwrap();
    });
    writer.finish().unwrap();
    let buf = writer.into_inner();

    let bar = String::from_utf8(buf).unwrap();
    let mut file = File::create("example_lines.txt").unwrap();
    file.write_all(bar.as_ref()).unwrap();
```

Am I using the wrong type of file reader?

**Comment by jorgecarleitao** [comment]
Hey! Thank you for your kind words 🙇

The issue seems to be that you are using `read_file_metadata` to read a stream's metadata.

The idea is that Arrow has two IPC formats, "File" and "Stream". To read a file metadata, use `read_file_metadata`; to read the stream's metadata, use `read_stream_metadata`.

The content seems to be a stream (as `StreamReader` is being used in the arrow version).

Could you try that?

**Comment by joshuataylor** [comment]
Yes, I just read that in the docs, I'm an idiot -- thanks!

For future readers who run into this -- [read this](https://jorgecarleitao.github.io/arrow2/io/ipc_stream_read.html):

Quick code snippet:
```
    let mut file = File::open("example_snowflake_data").unwrap();
    let metadata = read::read_stream_metadata(&mut file).unwrap();
    let mut stream = read::StreamReader::new(&mut file, metadata);
```

:man_facepalming:

**Comment by jorgecarleitao** [comment]
Great that it work out.

imo "Arrow IPC file" and "Arrow IPC stream" can be confusing: we can have a (filesystem) "file" containing an Arrow IPC Stream - do we call it a file or a stream?
