### ISSUE TITLE
Support projection to IPC streams

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/arrow2#1095]

**Comment by joshuataylor** [comment]
Ha! I just came here to create an issue, asking if this was something that could be done.

I've started looking into it.

**Comment by jorgecarleitao** [comment]
Let me know if you need help - it seems that we need to accept `projection` and push it through the functions up to `read_next`, like we do for `FileReader`.

**Comment by joshuataylor** [comment]
Yep, that's what I'm guessing too. It should be fairly straight forward, and pretty much the same implementation as the file reader, also with similar tests.

Good first issue :)
