### ISSUE TITLE
Make build of guide part of the CI

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/arrow2#11]
Currently we build and deploy it in main, but we do not build it in PRs, which may cause main to fail.

**Comment by Jibbow** [comment]
Hi, I just stumbled across this project and it looks quite promising! I can pick this issue up if you want. Just for clarification:
 * should the guide be built on every push to a branch or _only_ for a PR (and, of course, on `main`)?
 * should it only be built when files in the `guide/` directory change?

**Comment by jorgecarleitao** [comment]
Hi @Jibbow , thanks for your interest!

The build process is just a few seconds. imo it helps when people push a branch and the CI is triggered, as it helps them during dev (e.g. push and see if it flies). It can be only when `guide/` is changes, anything would also be fine. :)

note: we already test the examples in docs as part of the tests.

**Comment by jorgecarleitao** [comment]
Closed by #20 . Thanks a lot @Jibbow !
