### ISSUE TITLE
`std::simd::Simd::lanes_eq` no longer present in latest nightly

### ISSUE THREAD

**Issue by gyscos** [jorgecarleitao/arrow2#1184]
As of rustc 1.64.0-nightly (7fe022f5a 2022-07-24), `std::simd::Simd` no longer exposes a `lanes_eq` function.

https://doc.rust-lang.org/nightly/std/simd/struct.Simd.html

Seems to be the result from this PR: https://github.com/rust-lang/portable-simd/pull/265

Merged by https://github.com/rust-lang/rust/pull/99491

**Comment by jorgecarleitao** [comment]
Hey @gyscos - thanks for this. Would you like to try to fix it, or should I do it?

**Comment by gyscos** [comment]
I can try! Just pushed a PR with a fix.
