### ISSUE TITLE
parquet_write example no longer working

### ISSUE THREAD

**Issue by rajasekarv** [jorgecarleitao/arrow2#1187]
cargo run --release --example parquet_write --all-features produces

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgumentError("The datatype Int32 cannot be encoded by RleDictionary")', /home/raja/work/rust/arrow2/src/io/parquet/write/row_group.rs:39:90

**Comment by jorgecarleitao** [comment]
Hey @rajasekarv , oops, sorry for that - basically we need to use `Encoding::Plain` encoding for non-dictionary-encoded arrow arrays.

Would you like me to fix it, or should you?

**Comment by rajasekarv** [comment]
Hi @jorgecarleitao . I knew the issue. Just pointed out that it is no longer compiling. Will raise a PR with the fix.
