### ISSUE TITLE
Is it possible to borrow a reference to the child data which lives as long as the parent?

### ISSUE THREAD

**Issue by teymour-aldridge** [jorgecarleitao/arrow2#1219]
In some cases (e.g. when trying to build iterators on top of arrow2 types), it would be very helpful to be able to create a reference to a parent's child which has the same lifetime as the parent. For example, in arrow-rs there is a method called [child_data](https://docs.rs/arrow/latest/arrow/array/struct.ArrayData.html#method.child_data) which returns a reference to the children arrays with the same lifetime as the parent.

Is it possible to do this in arrow2 (I've searched through the documentation but couldn't find anything so I'm unsure)?

**Comment by jorgecarleitao** [comment]
Hey @teymour-aldridge, thanks for trying arrow2!

For strong typed iterators, you need to get the children, each array type has its own method of exposing its children. For example,

* [`ListArray::values`](https://docs.rs/arrow2/latest/arrow2/array/struct.ListArray.html#method.values)
* [`StructArray::values`](https://docs.rs/arrow2/latest/arrow2/array/struct.StructArray.html#method.values)
* [`FixedSizeListArray::values`](https://docs.rs/arrow2/latest/arrow2/array/struct.FixedSizeListArray.html#method.values)

For dynamic-typed iterators, we have [`iter`](https://docs.rs/arrow2/latest/arrow2/array/struct.StructArray.html#method.iter) on all arrays, which return an `Iterator<Item=Option<Box<dyn Scalar>>>` (so one allocation per item, which may be too expensive, but sometimes is necessary).

Would any of these APIs help for your use-case?
