### ISSUE TITLE
Bitmap slice doesn't match debug representation

### ISSUE THREAD

**Issue by teymour-aldridge** [jorgecarleitao/arrow2#1224]
When obtaining the bitmap as a slice I think there may be a bug in the handling. For example, in this program I've written (below), when I run it, the first assertion passes, but the second fails giving 

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `([173], 0, 7)`,
 right: `([45], 0, 7)`', src/main.rs:20:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think that here the bit in position 0 (or 7 in little-endian) has been erroneously set (it is the only bit which is different in 173 base 2 than in 45 base 2. Especially as the start offset is set as zero.

```
use arrow2::array::{ListArray, MutableListArray, MutablePrimitiveArray, TryExtend};

fn main() {
    let data = vec![
        Some(vec![Some(1), None, Some(2), Some(4), Some(1), None]),
        None,
        Some(vec![Some(1), None, Some(8), Some(4), Some(1), None]),
        Some(vec![Some(1), None, Some(2), Some(4), Some(1), None]),
        None,
        Some(vec![Some(1), None, Some(2), Some(4), Some(1), None]),
        None,
    ];

    let mut mutable_list = MutableListArray::<i32, MutablePrimitiveArray<i32>>::new();
    mutable_list.try_extend(data.clone()).unwrap();
    let list: ListArray<i32> = mutable_list.into();
    let list = list.arced();
    let bitmap = list.validity().unwrap();
    assert_eq!(format!("{:?}", bitmap), "[0b_0101101]");
    assert_eq!(bitmap.as_slice(), (vec![0b0101101 as u8].as_slice(), 0, 7))
}
```

**Comment by jorgecarleitao** [comment]
The issue here is that `0b_0101101` represents: the bitmap with 7 bits (the last one is undetermined). I.e. the `_` stands for undetermined. In this case, it is actually a `1`:

```rust
assert_eq!(bitmap.as_slice(), (vec![0b10101101 as u8].as_slice(), 0, 7))
```

The technical reason it is a 1 and not a zero is that up to the point where we have not observed a null value in the iterator, the validity is `None`. Once we observe the first null, we need to initialize a new validity with `1`s up to the current length, something like

```rust
let mut validity = vec![1; (self.len() + 7) / 8];
unset_bit(&mut validity, self.len());
self.validity = Some(validity)
````

**Comment by jorgecarleitao** [comment]
@teymour-aldridge , would it be ok to close this issue?
