### ISSUE TITLE
Example Request: reading parquet into vectors

### ISSUE THREAD

**Issue by peridotml** [jorgecarleitao/arrow2#1242]
Hello! I was hoping to read two columns of parquet into `Vec<usize>`'s using the package directly. I was able to hack something together, but it would be really great to get some help to do it really well. I have been reading through the docs and examples, but I am pretty stuck.

With a little direction on the steps of how to do it, I would put together an example if you think that is useful! It would have been to me :). 

This my use-case:
I work at a streaming tv / movie company and we are doing recommenders using sparse matrices. In python or Spark it requires tons of memory, but in rust I could easily handle 125m rows on my Macbook air. Completely incredible!

**Comment by jorgecarleitao** [comment]
Hi!

Thank you for considering arrow2 :)

Have you tried this? https://github.com/jorgecarleitao/arrow2/blob/main/examples/parquet_read.rs

The idea is:

```rust

// use the example above to get a chunk (or multiple, if you want to process in chunks)
let chunk = ...;

// deconstruct it into arrays
let arrays = chunk.into_arrays();

// get the individual arrays (assuming i32, could be i64 if the parquet columns are i64)
let c0 = arrays[0]
        .as_any()
        .downcast_ref::<PrimitiveArray<i32>>()
        .unwrap();

let c1 = arrays[1]
        .as_any()
        .downcast_ref::<PrimitiveArray<i32>>()
        .unwrap();

// convert them to `Vec<usize>`
// note that the below disregards the arrays' validities.
let c0: Vec<usize> = c0.values().into_iter().map(|x| x as usize).collect();
let c1: Vec<usize> = c1.values().into_iter().map(|x| x as usize).collect();
```
