### ISSUE TITLE
Potentially unneeded call in Parquet repetition-level encoding

### ISSUE THREAD

**Issue by dexterduck** [jorgecarleitao/arrow2#1254]
In `io::parquet::write::nested::write_rep_levels` it appears that [lines `40-41`](https://github.com/jorgecarleitao/arrow2/blob/main/src/io/parquet/write/nested/mod.rs#L41) are unnecessary. 

As far as I can tell it writes to buffer that's never used anywhere else, and I can't identify any relevant side-effects. 

@jorgecarleitao Is it safe to remove? The extra call to `RepLevelsIter` adds a pretty substantial overhead when writing nested data.

**Comment by jorgecarleitao** [comment]
Woops, yes, safe to remove! It is a leftover from debugging :/
