### ISSUE TITLE
MutableUtf8Array offsets bug

### ISSUE THREAD

**Issue by xinnosuke** [jorgecarleitao/arrow2#1256]
When new MutableUtf8Array is created, it sets offsets to default 0.
But when creating Array from the MutableArray, it removes the offsets, including the initial offset 0.
And if you want to push a new value after this, it will not add back the initial offset 0, but the size of the new value.
Additionally, if the first value is a null value, it will be an error because it will try to get the last offset which is a None value.

  ```
  fn test_mut_utf8() {
        let mut mut_array: MutableUtf8Array<i32> = MutableUtf8Array::new();
  
        for i in 0..20 {
            if i == 10 {
                let array = mut_array.as_box();

                // panics
                // mut_array.push_null();
            }
            mut_array.try_push(Some(i.to_string())).unwrap();
        }
        let array = mut_array.as_box();

        // assert fails
        assert_eq!(array.len(), 10);
    }
```

**Comment by jorgecarleitao** [comment]
Being fixed as part of #1260

**Comment by snaar** [comment]
Can you possibly add something as the example test code in this issue as a unit test? I took a look at #1260 but I didn't quite see this use case tested - it's possible I just didn't read carefully enough.

**Comment by jorgecarleitao** [comment]
Here: https://github.com/jorgecarleitao/arrow2/pull/1266

The root cause was that `as_box` was `std::mem::take`ing the offset `vec`, leading to an empty offset vector (it should always contain a 0). This was causing the mutable to become invalid when re-used.
