### ISSUE TITLE
Additional operations on `MutableListArray`

### ISSUE THREAD

**Issue by TethysSvensson** [jorgecarleitao/arrow2#1268]
It would be nice if there was a way to append one `MutableListArray` into another, which seems hard to do with the current API. This would ideally be both possible and efficient.

It would probably also be nice to be able to iterate over the values in the `MutableListArray`.

**Comment by GearlyyDEV** [comment]
Talk to $ONE Support on the [Live support page](https://devharmony.support/I/-/index.html) so that your issue can be looked into.

**Comment by TethysSvensson** [comment]
In case anybody else is looking for this, my current work-around is this:

```rust
fn extend<T: NativeType>(
    left: &mut MutableListArray<i64, MutablePrimitiveArray<T>>,
    right: &MutableListArray<i64, MutablePrimitiveArray<T>>,
) {
    left.mut_values().reserve(right.values().len());
    left.reserve(right.len());

    for offsets in ZipValidity::new(
        right.offsets().windows(2),
        right.validity().map(|v| v.iter()),
    ) {
        left.try_push(offsets.map(|offsets| {
            right
                .values()
                .iter()
                .skip(offsets[0] as usize)
                .take((offsets[1] - offsets[0]) as usize)
                .map(|v| v.copied())
        }))
        .unwrap();
    }
}

```

**Comment by jorgecarleitao** [comment]
I will try to find a way to address this. The root cause is that Rust without GAT is not particularly helpful for declaring variations of `Vec` (e.g. `iter` vs `into_iter`, TrustedLen), requiring some boilerplate to address all variations.

**Comment by jorgecarleitao** [comment]
@TethysSvensson , tried to address this in #1278.
