### ISSUE TITLE
Reconsider forbid unsafe

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#1306]
I think we should reconsider `forbid_unsafe` on the IO module. Currently we are having redundant checks in the parquet reader that are perfectly sound to elide.

I saw that in my local benchmarks 10% of samples were in `check_offsets` when converting a `Binary<O>` to a `Utf8Array`. I believe that these offsets never have to be checked as they are created by us and are not read from disk. I think we only should check utf8 in that case.

We could probably create a safe wrapper around a `from` implementation, but that still requires `unsafe`.

**Comment by jorgecarleitao** [comment]
I think that we were able to achieve this without unsafe in IO, right?

I agree that `unsafe` may be required in IO - part of the reason to not have it is to force us to write abstractions that reduce the use of `unsafe` outside of the "core".

**Comment by ritchie46** [comment]
Yeap, we were. :) At least utilize `unsafe` in another module. Will close as the goal is achieved :+1:.
