### ISSUE TITLE
Parquet writes all values of sliced arrays? 

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#1323]
During parquet writes we write smaller pages because of the `i32::limit` and because of performance improvements when writing smaller pages during reading.

Nested structures such as lists and utf8 are then sliced by their offsets, but the whole values are then send to the pages writer. I haven't yet confirmed this, but I believe this is what happens and is the reason for:

1: invalid parquet files
2: extreme memory usage
3: extreme file sizes

all reported in: https://github.com/pola-rs/polars/issues/4393

**Comment by ritchie46** [comment]
The parquet size also seems to grow exponential.

```python
import os
import polars as pl 
import numpy as np

x = np.arange(100, step=10)
pas = []
pls = []
for i in x:
    df = pl.DataFrame({'listIntCol': [[1,1,1], [1,2,3], [None,2,None]]*int(i * 1e4)})
    df.write_parquet('test-T1.parquet', use_pyarrow=True)
    df.write_parquet('test-T2.parquet', use_pyarrow=False)

    t1 = os.path.getsize('test-T1.parquet') / 1000
    t2 = os.path.getsize('test-T2.parquet') / 1000
    pas.append(t1)
    pls.append(t2)

print(f'{t1=:,.0f} kb, {t2=:,.0f} kb')

plt.plot(x, pas, label="pyarrow")
plt.plot(x, pls, label="arrow2")
plt.title("mem usage")
plt.xlabel("df size")
plt.ylabel("parquet size")
plt.legend()
```
![image](https://user-images.githubusercontent.com/3023000/206894256-18627142-4d8f-4810-a634-4159e73a830a.png)

**Comment by ritchie46** [comment]
Confirmed that it write all values and doesn't take offsets into account. The written files are incorrect and write/read a lot of unneeded values. Working on a fix.

![image](https://user-images.githubusercontent.com/3023000/206912052-cc7343c2-05f1-42c3-b20d-a7e4f1d6af50.png)

**Comment by tjwilson90** [comment]
This still appears to be a problem, see https://github.com/jorgecarleitao/arrow2/issues/1356#issuecomment-1399396188
