### ISSUE TITLE
Async Parquet Reader: Re-downloads blocks?

### ISSUE THREAD

**Issue by bjchambers** [jorgecarleitao/arrow2#1332]
The "factory" that is passed to the Async Parquet reading code must by `AsyncSeek` and `AsyncRead`, but is only used to download one block (based on the example) via a `seek` and `get`. At the same time, if this is fetching from S3 or similar object stores it may be desirable to issue fewer "gets" (for a 10MB chunk, say), and share that between multiple reads (multiple calls to the factory).

Are there thoughts on how to best support this. There seem to be two options:

1. Have something that implements `AsyncSeek` and `AsyncRead` via some kind of central cache. This would need to manage the blocks being fetched to perform sharing, and also deal with the fact that too many blocks in the cache would increase memory pressure.
2. Another thought given the above is that the factory shouldn't need to be an `AsyncRead` (and in fact, it may be easier if it wasn't). If instead, the factory was `async fn fetch(start: usize, len: usize) -> Result<Bytes>` indicating the range of bytes it wished to receive, then (i) users wouldn't need to implement the `AsyncRead` and `AsyncSeek` traits, and instead the factory itself could manage the block cache. Additionally, if there were some kind of reference counted "byte slice", it could be possible for the returned bytes to just be a pointer into that block cache.

I guess I'm not sure how a user of the library is *supposed* to manage the async fetching of blocks when using the parquet reading, especially when combined with something like `object_store`. Is there any guidance on this written down anywhere?

**Comment by sundy-li** [comment]
Better fetch data from s3 via an async read API to `Vec<u8>` and use sync read API to deserialize a chunk.

**Comment by bjchambers** [comment]
That makes sense. I was hoping to find a way to only fetch the ranges for needed columns (if the file was large), etc. 

I’ll probably go with fetching the whole file for now, but it seems like that could lead to memory pressure when working with many files, etc.

Thanks for confirming that that route at least makes sense for now and there wasn’t something better already available!

**Comment by sundy-li** [comment]
>  I was hoping to find a way to only fetch the ranges for needed columns

You can fetch the meta in previous and get the ranges of each column. This is a very trivial cost because you just need read less metadata per file.

**Comment by tustvold** [comment]
> I was hoping to find a way to only fetch the ranges for needed columns
>  If instead, the factory was async fn fetch(start: usize, len: usize) -> Result<Bytes>

FWIW this is the approach that the [async parquet reader](https://docs.rs/parquet/latest/parquet/arrow/async_reader/index.html) in arrow-rs uses, you may be able to [crib from it](https://github.com/apache/arrow-rs/blob/master/parquet/src/arrow/async_reader.rs#L378). Not only does this translate more cleanly to object stores, but also allows coalescing adjacent bytes ranges together to reduce the number of requests. This approach even helps local file IO because `tokio::fs` currently calls `spawn_blocking` for every API call and is therefore surprisingly expensive
