### ISSUE TITLE
Target-specific features not supported by Cargo

### ISSUE THREAD

**Issue by ankane** [jorgecarleitao/arrow2#1358]
Hi, hope your year is off to a good start.

Cargo doesn't currently support target-specific features (https://github.com/rust-lang/cargo/issues/1197), so the pattern used in #1297 ends up enabling both the `compile-time-rng` and `runtime-rng` features of `ahash` on all platforms.

https://github.com/jorgecarleitao/arrow2/blob/211be21991c29c235253a19413f43a76a367955f/Cargo.toml#L100-L106

This pulls in the dependencies for both on all platforms.

**Comment by hzuo** [comment]
Should be fixed by https://github.com/jorgecarleitao/arrow2/pull/1407

**Comment by ankane** [comment]
Thanks @hzuo!
