### ISSUE TITLE
Support for mode as a write option

### ISSUE THREAD

**Issue by chitralverma** [jorgecarleitao/arrow2#1365]
While writing parquet or other formats it will be great to have a `mode` write option similar to that available in Apache Spark API. This will allow users to append, overwrite or error if the parquets already exist at the provided destination.

From the code I couldn't find a way to do this yet.

**Comment by jorgecarleitao** [comment]
Hi @chitralverma . This is controlled by how you open the file (that implements `std::io::Write`) - we do not control this directly in the library as you as user can already control how the implementor of `Write` is initialized.

In our specific example where we write a parquet file to disk, this is the relevant line: https://github.com/jorgecarleitao/arrow2/blob/main/examples/parquet_write.rs#L33

I hope this makes sense!

**Comment by chitralverma** [comment]
Got it, thanks.
