### ISSUE TITLE
Any plans for Python Bindings?

### ISSUE THREAD

**Issue by aersam** [jorgecarleitao/arrow2#1388]
Well, the title says it: I'd like to use this library from python, however thats not easily possible for now?

**Comment by jorgecarleitao** [comment]
You have [polars](https://pola.rs) and [arrowdantic](https://pypi.org/project/arrowdantic/) - one is a fully fledged query engine, the other is a thin wrapper of arrow2 :)

**Comment by aersam** [comment]
Yeah, saw that , that why I closed it so fast :) sorry for opening it anyway
