### ISSUE TITLE
Example of identifying and only loading/decompressing row-groups/chunks/pages for a specific row

### ISSUE THREAD

**Issue by mpetri** [jorgecarleitao/arrow2#1417]
Hello,

suppose I have code that finds (based on a cheap column to decode) a specific row for which I want all columns. How would I go about that?

From what I see from the example I would need to store as "location" of that row:

- The row group,
- The chunk id?
- the overall row id in that chunk?

Is there a way to read/decompress the minimal amount to get the all columns for this specific row? 

```
    let metadata = read::read_metadata_async(&mut reader).await?;
    let schema = read::infer_schema(&metadata)?;
    let target_row_group = 0;
    let row_group = metadata.row_groups[target_row_group];
    let column_chunks = read::read_columns_many_async(
        factory,
        row_group,
        schema.fields,
        None,
        None,
        None,
    )
    .await?;
    let column_chunks = read::read_columns_many_async(
        factory,
        row_group,
        schema.fields.clone(),
        None,
        None,
        None,
    )
    .await?;
    let target_chunk_id = 2;
    let serialized_chunk = column_chunks[target_chunk_id];
    let chunk = RowGroupDeserializer::new(vec![serialized_chunk], row_group.num_rows(), None);
    let target_row = 12;
    for column in chunk.columns() {
        let row = column.slice(target_row, 1);
        // do stuff with row
    }
```

this is a sketch of what I could come up with. Am I missing any efficiency improvements that I could make here?

**Comment by mpetri** [comment]
Looking back at this. I think I'm doing this wrong as a row would span multiple column chunks. Any example or pointers? Would page filters help?

**Comment by ozgrakkurt** [comment]
Hey,

I am assuming you mean parquet.

A file consists of row groups, row groups consist of column chunks and column chunks consist of column pages. So you have the ability to skip down to column pages. If you want only one row you'd need to identify that row first loading the columns you want to filter by then you can load the rest of the columns for that row.

**Comment by mpetri** [comment]
Thanks @ozgrakkurt. I got as far as being able to iterate over `column chunks` (see example above) but I'm unclear how I go from column chunks to column pages. I see the [get_page_iterator](https://docs.rs/arrow2/0.16.0/arrow2/io/parquet/read/fn.get_page_iterator.html) function but not sure how to extend the example above to only load/decompress the actual pages I need. 

Do you know any sample code that does that?

**Comment by ozgrakkurt** [comment]
I don't have in unfortunately and afaik most libraries don't even implement it. But it seems possible with arrow2 API.

**Comment by mpetri** [comment]
Thanks. I tried making this work but couldn't figure it out. Maybe I'll close this issue as it does not really seem like a bug of the library.
