### ISSUE TITLE
ORC file format support

### ISSUE THREAD

**Issue by hinxx** [jorgecarleitao/arrow2#1422]
I would use arrow2 with polars and I want to work with ORC file format. How complete is the ORC file format support? Is there support for unions? Are there any missing features?

**Comment by ozgrakkurt** [comment]
Hey,

you can see:
- https://github.com/DataEngineeringLabs/orc-format
- https://docs.rs/arrow2/latest/arrow2/io/orc/index.html

**Comment by jorgecarleitao** [comment]
Hi @hinxx - we only support basic ORC types atm. No union support yet.
