### ISSUE TITLE
Mutable dictionary array is wrong

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#1485]
It stores the hash as a key, but doesn't do any key comparison on insert. Though the probability of collisions is low, it is not zero, so for certain inputs the keys will collide and produce invalid arrays.

**Comment by aldanor** [comment]
@ritchie46 Any suggestions on what's the proper way to handle hash collisions?

**Comment by aldanor** [comment]
You mean the "values" (in terms of `MutableDictionaryArray<K, V>`)? But then we'd need to change its signature to `MutableDictionary<K, V, T>` and it will become pretty weird re: linking `T` and `V` together, no?

**Comment by aldanor** [comment]
E.g., we currently have
```rust
impl<O, T> TryPush<Option<T>> for MutableUtf8Array<O>
where
    O: Offset,
    T: AsRef<str>,
{}

impl<K, M, T> TryPush<Option<T>> for MutableDictionaryArray<K, V>
where
    K: DictionaryKey,
    M: MutableArray + TryPush<Option<T>>,
    T: Hash,
{}
```
If you change it to
```rust
MutableDictionaryArray<K, V, T>
```
then you'd need some way of converting values that are being pushed (e.g. `&str`) into values that are stored in the hashmap (e.g. `String`).

```rust
impl<K, M, T> TryPush<Option<X>> for MutableDictionaryArray<K, V, T>
where
    K: DictionaryKey,
    M: MutableArray + TryPush<Option<T>>,
    X: Hash,
    T: Into<X>, // <--- ?
{}
```

**Comment by aldanor** [comment]
I guess another way is adding a trait that would map `V: MutableArray -> T` and implement it for all basic types, so then the signature can be kept as `<K, V>`; not sure it's doable though, and how it would work with more complex types other than basic scalars and strings...

**Comment by aldanor** [comment]
Ok, here's one weird idea... :) 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021

(replace `PinnedVec<T>` with a sub-trait of `MutableArray` that knows how to get an item reference at given index for comparison and hashing)

**Comment by aldanor** [comment]
(Link to the playground was wrong, updated ^)
