### ISSUE TITLE
Why not use unsigned physical representation  for Date/DateTime types

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#206]
```

| `DataType`            | `PhysicalType`            |
|-----------------------|---------------------------|
| `Date32`              | `PrimitiveArray<i32>`     |
| `Date64`              | `PrimitiveArray<i64>`     |
| `Time32(_)`           | `PrimitiveArray<i32>`     |
| `Time64(_)`           | `PrimitiveArray<i64>`     |
```

Since the `Date` represents the time elapsed time since the UNIX epoch, So I wonder why not use unsigned physical representation for these types.

**Comment by sundy-li** [comment]
Is it because Java did not support unsigned types?

**Comment by jorgecarleitao** [comment]
Had the same question when I started using arrow. The same happens for the utf8 array, on which the offsets are `i32/i64`. This is part of the arrow spec and I believe that you are right: it was probably motivated by Java. 👍

**Comment by sundy-li** [comment]
Thanks, And what will happen if we use a negative number in `Date32`? 

So the large date in Date32 will just be ` 65535/ 365 ~ 180 years from  1970`, I doubt my grandson will be in trouble using this Data32 Types...

**Comment by jorgecarleitao** [comment]
I think that negative dates are just counted backwards in time since 1970.

**Comment by sundy-li** [comment]
Thanks for the information.
