### ISSUE TITLE
Question about the performance with official arrow

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#224]
Hello, I have a question about the performance result with the official arrow crate.

From doc: https://docs.google.com/spreadsheets/d/1hLKsqJaw_VLjtJCgQ635R9iHDNYwZscE0OT1omdZuwg/edit#gid=0

Why `arrow2` has better performance in **sum array with all null**? 

From the codes, I figure out both crates used packed_simd into vectorized execution. I did not see any reason that could make sense to gain the performance.

**Comment by jorgecarleitao** [comment]
My current hypothesis is that it is related to 
* how arrow2 loads packs from the heap to the stack in the hot loop
* how arrow2 performs the intermediary sum (that is also SIMD)

but never digged into the details. The relevant code is here: https://github.com/jorgecarleitao/arrow2/blob/main/src/compute/aggregate/sum.rs#L21 

In general, `packed_simd` is just an abstraction to compile to specific instructions; there is still some degrees of freedom in how they are used.
