### ISSUE TITLE
Investigate how to add support for timezones in timestamp

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/arrow2#23]
We currently support timezones at logical level, via `Timestamp(_, tz)`, but have no mechanism to perform operations with them, The goal is to investigate how to add support for them. This will likely require depending on [chrono-tz](https://docs.rs/chrono-tz/0.5.3/chrono_tz/).

A simple concrete goal here is to add support to `cast` from and to `Timestamp(_, str)` and `Timestamp(_, None)`.

A question here is how we represent these things: it seems that in `chrono-tz`, timezones are static types (i.e. struct), while timezones in Arrow are dynamic (i.e. `str`).

**Comment by elferherrera** [comment]
What happened to this one? Did you managed to get timezones working?

**Comment by jorgecarleitao** [comment]
There has been some discussions over the mailing list on how timezones should be treated, so I have not touched this. It seems that they have settled, though.

**Comment by elferherrera** [comment]
I didnt follow the mailing list, sorry. What was the final solution at the end?

**Comment by jorgecarleitao** [comment]
@elferherrera , being done in #376 . Took a bit to understand what was that about. It would be great if you could take a look.
