### ISSUE TITLE
Array support get_array_memory_size 

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#241]
https://github.com/apache/arrow-rs/blob/master/arrow/src/array/array.rs#L209-L213

**Comment by jorgecarleitao** [comment]
It is under `compute::aggregate::memory`, https://github.com/jorgecarleitao/arrow2/blob/main/src/compute/aggregate/memory.rs

**Comment by sundy-li** [comment]
Thanks, that's what I need
