### ISSUE TITLE
Question about `flight_data_to_arrow_batch` is_little_endian endian option

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#244]
I found arrow2 introduce a  new  option named `is_little_endian` in  `flight_data_to_arrow_batch`:
   https://github.com/jorgecarleitao/arrow2/blob/main/arrow-flight/src/utils.rs#L147-L152

I don't know for what reason to introduce this parameter.

Will this make the  interaction between different architecture platforms be not compatible?

 
 Thanks

**Comment by jorgecarleitao** [comment]
The Arrow IPC format accepts writing values in big endian: it is part of the specification. When reading from IPC, arrow2 needs to know whether the serialized data is little or big endian to correctly swap bytes if `platform endianess != file endianess`.

Arrow-rs does not check the endianess of the IPC file and assumes that it is little endian.

**Comment by sundy-li** [comment]
Ok, since we have `flight_data_from_arrow_batch` and `flight_data_to_arrow_batch`

1.  `flight_data_from_arrow_batch` can convert RecordBatch to flight data without option `is_little_endian`
2.  But in my server[intel I5 X86 ubuntu], use  `flight_data_to_arrow_batch`to convert flight data to record batch, I must set the `is_little_endian` to true, otherwise it'll throw error.

https://github.com/sundy-li/learn/blob/master/arrow-vs-arrow2/examples/appender.rs
