### ISSUE TITLE
Improve rem_scalar/div_scalar  performance

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#259]
Refer to:

Blog: https://lemire.me/blog/2019/02/08/faster-remainders-when-the-divisor-is-a-constant-beating-compilers-and-libdivide/
Paper:  https://arxiv.org/abs/1902.01961
Go: https://github.com/bmkessler/fastdiv
Rust: https://docs.rs/strength_reduce/0.2.3/strength_reduce/

**Comment by lideen999** [comment]
Fuse processing number% 3 is slow. The main reason is that type conversion is made every time. I try to remove type conversion. The performance can be 2G -- > 5G / s

**Comment by sundy-li** [comment]
@lideen999  

#252 shows the main reason cast.

I did some perfs in datafuse, seems the rem is the hot path.

**Comment by sundy-li** [comment]
@jorgecarleitao   

By using `strength_reduce`, it shows great improvement in datafuse.

**Comment by jorgecarleitao** [comment]
This is a valid request: valid use-case, documented benefits, crate with implementation available. 👍

Would you like to work on it, or would you like me to take it?

Also, I went through the crate and is `unsafe` free, so even easier sell.

**Comment by ritchie46** [comment]
The same optimization can be used for division as well right?

**Comment by sundy-li** [comment]
> The same optimization can be used for division as well right?

Yes! Of course.

> Would you like to work on it, or would you like me to take it?

Sorry, currently I may have no time to work on it, I just provide this idea to make arrow2 work better.

**Comment by jorgecarleitao** [comment]
Done in #275
