### ISSUE TITLE
Async reader for parquet file

### ISSUE THREAD

**Issue by leiysky** [jorgecarleitao/arrow2#319]
I've just noticed that there is an issue about this in arrow repo https://github.com/apache/arrow-rs/issues/111.

Is there any plan on this?

**Comment by BohuTANG** [comment]
May be this helpful:
https://github.com/jorgecarleitao/arrow2/pull/260

**Comment by jorgecarleitao** [comment]
Closed by #260 . Thanks @BohuTANG !
