### ISSUE TITLE
Provide a Rc version of the arrow API?

### ISSUE THREAD

**Issue by yjhmelody** [jorgecarleitao/arrow2#341]
For a no_std environment like wasm, is it more efficient to provide a Rc version of the API?

**Comment by jorgecarleitao** [comment]
Ok. That would be a major change to all other use cases that require shared memory (FFI, IPC, multi-threads). Usually in Arrow the operations themselves on the data are much more expensive than the `Arc` vs `Rc`.

Could you clarify which type of operations you expect to expect `Arc` to be much worse than `Rc` on those operations?
