### ISSUE TITLE
`StringRecord` is undocumented 

### ISSUE THREAD

**Issue by HagaiHargil** [jorgecarleitao/arrow2#356]
Hi,

While trying to use the CSV reader I noticed that I couldn't find any docs about `StringRecord`, even though it's a public type that is returned from the `records()` methods. After a bit of digging I discovered that it's probably the `csv` crate type, even though the docs point to an internal (and non-existent) type, much like `ByteRecord`.

**Comment by jorgecarleitao** [comment]
I could not find a public `StringRecord`. How are you importing it from `arrow2`?

**Comment by HagaiHargil** [comment]
The CSV [Reader]([https://docs.rs/arrow2/0.4.0/arrow2/io/csv/read/struct.Reader.html) has a few, although now I see that they do lead to the CSV crate when I click on them. Not sure how I missed that last time, so perhaps this isn't a real issue. Sorry.
