### ISSUE TITLE
Async parquet write

### ISSUE THREAD

**Issue by GrandChaman** [jorgecarleitao/arrow2#371]
Hi !

First of all thanks for this library !

Would it be possible to add support for writing parquet file asynchronously ?

`parquet2` already implements such function.

**Comment by jorgecarleitao** [comment]
Just to clarify, there are 4 cases of interest:

* consumer: `Write`; producer: `Iterator`
* consumer: `AsyncWrite`; producer: `Iterator`

**Comment by jorgecarleitao** [comment]
sorry, wrong combination of keys :(; will update comment above

**Comment by jorgecarleitao** [comment]
@GrandChaman there :)

**Comment by GrandChaman** [comment]
Yes, exactly. 

From what I understand `1` and `2` already exists.
I think it'd be nice to add support for `4`.

Maybe there's no need for `3` as one could make a `Stream` from an `Iterator` ?
