### ISSUE TITLE
[0.5] The docs `io` module has no submodules

### ISSUE THREAD

**Issue by HagaiHargil** [jorgecarleitao/arrow2#390]
Congrats on the new release!

Navigating to [here](https://docs.rs/arrow2/0.5.0/arrow2/io/index.html), I can't seem to reach any submodules of the `io` module, such as IPC.

The symbols that are defined there are also missing from the docs as a result.

**Comment by jorgecarleitao** [comment]
Thanks a lot for noticing and reporting back! I made a hot fix for this. It also adds some labels to the features that are required to each part of the docs, e.g. https://docs.rs/arrow2/0.5.2/arrow2/compute/index.html

**Comment by HagaiHargil** [comment]
Happy to help!

I actually looked for a "good first issue" label around but couldn't find any issue to tackle.

**Comment by jorgecarleitao** [comment]
Good point, @HagaiHargil , I started to identify some of them and will continue to do so in the following days.
