### ISSUE TITLE
Implement dictionary required for binary parquet data

### ISSUE THREAD

**Issue by Dandandan** [jorgecarleitao/arrow2#418]
I got this error when trying out arrow2 on Parquet data via DataFusion / TPC-H benchmark.

```Error: ArrowError(External("", ArrowError(External("", Execution("Arrow error: Not yet implemented: Decoding \"RleDictionary\"-encoded, dictionary-encoded required V1 pages is not yet implemented for Binary")))))```

**Comment by jorgecarleitao** [comment]
Datafusion only benchmarks with ideal data: who uses required fields in parquet in real life? ^_^

**Comment by Dandandan** [comment]
> Datafusion only benchmarks with ideal data: who uses required fields in parquet in real life? ^_^

LOL 😆

Not joking - I think IRL of data can be, especially expires from relational databases.
Also new tech like delta lake has (e.g. `non null`) constraints (not sure if it changes the parquet output though) now which hopefully means everyone is going to finally have good data quality 😂
