### ISSUE TITLE
Add `set` method to `MutableArray` trait

### ISSUE THREAD

**Issue by sd2k** [jorgecarleitao/arrow2#446]
Would it be possible to add the `set` method to the `MutableArray` trait? I see that a few `Mutable` arrays have this method (`MutableBooleanArray` and `MutablePrimitiveArray`) but it's missing from some. It'd be super helpful to have as part of `MutableArray` if all implementors could handle it!

Happy to send in a PR if you think this is doable.

**Comment by jorgecarleitao** [comment]
Hey! I understand the idea. Unfortunately, I do not think it is possible because it requires the trait to have the type `T` that is being set, and the trait does not have that information (right?)

**Comment by sd2k** [comment]
Ah yes of course - I just noticed I've been using the `TryPush` trait to construct mutable arrays generically. Perhaps a separate trait like that could work?

On a related note, is there a known reason why `MutableUtf8Array` doesn't have a `set` method?

Cheers!

**Comment by sd2k** [comment]
I went through the code to learn a bit more about this - I can see why `MutableUtf8Array` doesn't have that method now! I would still benefit from a `Set` method on `MutablePrimitiveArray<T>` and `MutableBooleanArray` but given that it's not possible for all types of `MutableArray` I think maybe this makes less sense - I can always write and implement that trait myself. Happy for this to be closed!

**Comment by jorgecarleitao** [comment]
=) Awesome that you found it yourself; it is not trivial to get the reason.

For those that are not following: `MutableUtf8Array` has an offset buffer containing the lengths of each item (e.g. `[0,2,5]` for `["12", "345"]`) and a values buffer e.g. `["1", "2", "3", "4", "5"]` for `["12", "345"]`. When we set an element and set it with a different length, we need to update all entries after the index. E.g. setting `"12a"` in the zero'th element of `["12", "345"]` amounts to:

* `[0,2,5] -> [0,3,6]`
* `["1", "2", "3", "4", "5"] -> ["1", "2", "a", "3", "4", "5"]`

which is `2 O(N-i)`

>  would still benefit from a Set method on `MutablePrimitiveArray<T>` and `MutableBooleanArray`

I think we have those already :)
