### ISSUE TITLE
Add `as_boxed` method to `MutableArray`

### ISSUE THREAD

**Issue by sd2k** [jorgecarleitao/arrow2#447]
`MutableArray` has `as_arc`, but not `as_boxed` (or `into_boxed`? not sure which is more appropriate) right now, although `GrowableArray` does - is this something you would consider adding? I have a use case which requires it to implement `Deserialize` for a `Box<dyn Array>` wrapper 🙂 

Happy to send in a PR if this sounds good. Thanks!

**Comment by jorgecarleitao** [comment]
Sounds great! Yes, in general it is good to have both methods. Rust does not have an idiomatic way of writing a function that can return either, so we need to do it ourselves 👍 

Thanks for volunteering for working on it; let me know if you get stuck :)
