### ISSUE TITLE
[DISCUSSION] add new versions of failable utf8 cast implementations

### ISSUE THREAD

**Issue by houqp** [jorgecarleitao/arrow2#457]
Postgres returns a syntax error when user tries to cast an non-numeric string to integers. The current cast compute module returns NULL when casting cannot be done. This makes it not possible to implement the same behavior in Datafusion (see comment in https://github.com/houqp/arrow-datafusion/pull/9/files#r716175200).

Is there any particular reason why we don't want to have a failable string cast implementation in arrow2?

**Comment by jorgecarleitao** [comment]
Because there is an easy way to compute them from the existing cast:

```rust
let array = ...
let result = cast(&array, data_type)?;

let some_cast_failed = result.null_count() == array.null_count();

let casted_and_valids = &result.validity().unwrap();
let valids = &array.validity().unwrap();
let failed_elements = casted_and_valids & &(!valids);
```

(or something like this). It is a bit more expensive and we can offer an optimized version of `casted_and_valids & &(!valids)` in bitmaps, but I felt that this would cover both cases pretty well.

**Comment by houqp** [comment]
Cool, i think this is a reasonable workaround to unblock the migration for now :) I was thinking of short-circuiting the cast on casting error when I filed this issue.
