### ISSUE TITLE
Publish arrow-flight to crates.io?

### ISSUE THREAD

**Issue by houqp** [jorgecarleitao/arrow2#463]
Needed for https://github.com/apache/arrow-datafusion/blob/558d8ecfe2d1b0737de1e2548c5fbedc0ea17ada/ballista/rust/core/Cargo.toml#L45 :)

**Comment by jorgecarleitao** [comment]
Agree. Let me prepare the infrastructure. I would prefer to move arrow-flight to another repo and release it from there, to not have 2 releases from the same repo, that more easily mix the changelogs, versioning, etc.

**Comment by jorgecarleitao** [comment]
@houqp , do you consider the current state of affairs sufficient? arrow-format tracks the service and struct declarations of the flight specification, and we track IO to and from those structs. I just released 0.7 that is compatible with arrow-format `0.3`, which is compatible with the latest prost and tonic.

**Comment by houqp** [comment]
Yes, what we have should cover ballista's use-case :)
