### ISSUE TITLE
cargo test only run unittests

### ISSUE THREAD

**Issue by xudong963** [jorgecarleitao/arrow2#524]
I run `cargo test --features full` locally, but only unit tests are run.

How to run integration tests (arrow2/tests) locally

**Comment by houqp** [comment]
you can find integration test commands based on CI tasks in .github/workflows, for example: https://github.com/jorgecarleitao/arrow2/blob/main/.github/workflows/integration-ipc.yml

**Comment by xudong963** [comment]
Thanks! Got it

I found the test need a data file and didn't find it in the project. Where can I fetch it?
```rust
    #[test]
    fn test_basic() -> Result<()> {
        if std::env::var("ARROW2_IGNORE_PARQUET").is_ok() {
            return Ok(());
        }
        let schema = read_schema("fixtures/pyarrow3/v1/basic_nullable_10.parquet")?;
        let names = schema
            .unwrap()
            .fields()
            .iter()
            .map(|x| x.name().clone())
            .collect::<Vec<_>>();
        assert_eq!(
            names,
            vec![
                "int64",
                "float64",
                "string",
                "bool",
                "date",
                "uint32",
                "string_large",
                "decimal_9",
                "decimal_18",
                "decimal_26"
            ]
        );
        Ok(())
    }
```

**Comment by jorgecarleitao** [comment]
Awesome. They are created via a Python script, See [here](https://github.com/jorgecarleitao/arrow2/blob/main/.github/workflows/test.yml#L17) for how we do it in the CI (I usually use a `venv`)

**Comment by jorgecarleitao** [comment]
One thing I usually do is to run the tests under feature gates. E.g. if my changes only affect csv, I use `cargo test --tests --features io_csv`
