### ISSUE TITLE
Add discoverability of supported types to each operation

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/arrow2#57]
`cast` has `can_cast`, IMO we should add `can_*` to every kernel, so that consumers can "poke" the operation, thereby allowing physical coercion rules to be applied before accessing the data.

**Comment by elferherrera** [comment]
Do you mean something like `can_add(datatype_a, datatype_b)`?

**Comment by elferherrera** [comment]
Ok. I think I get it. So, for each kernel we could have a function that can tell you if that type can perform that operation, and the arguments for that function will depend on the context of the kernel. For example, `concat` would be something like `can_concat(datatype)`. Whereas any arithmetic function would be `can_mul(datatype_a, datatype_b)`. Did I understand right?
