### ISSUE TITLE
Added `StreamWriter::into_inner`

### ISSUE THREAD

**Issue by dimasukr** [jorgecarleitao/arrow2#574]
Writer has [into_inner()](https://github.com/jorgecarleitao/arrow2/blob/main/src/io/ipc/write/writer.rs#L97) while StreamWriter lacks it.
I'm evaluating moving to Arrow2 from Arrow and there StreamWriter [has it](https://docs.rs/arrow/6.1.0/src/arrow/ipc/writer.rs.html#590-595) and we use it for tests and microbenchmarks

**Comment by jorgecarleitao** [comment]
Good catch, thanks! Done at #575.

**Comment by dimasukr** [comment]
Great thanks
Good that you removed Bufferer<W> as well because in my case Reader is already buffered so nice to have option not to double buffer

**Comment by jorgecarleitao** [comment]
Not sure what is your use-case, but you may also consider using the `async` version: https://github.com/jorgecarleitao/arrow2/pull/577

it currently blocks on serializing the batch to bytes, which is not optional, but it still concurrent on writing over the write ^_^
