### ISSUE TITLE
arrow2::io::ipc::read::reader::FileReader cannot set 0 as projection

### ISSUE THREAD

**Issue by illumination-k** [jorgecarleitao/arrow2#594]
Hi, Thanks for the very excellent project!

I would like to parse IPC files, but I cannot set 0 as projection like `arrow2::io::ipc::read::reader::FileReader::new(&mut reader, metadata, vec![0, 1])`. The cause of this seems to come from https://github.com/jorgecarleitao/arrow2/blob/add3e2a01068435f297197a28df885ab5bbf1653/src/io/ipc/read/reader.rs#L237-L243

If projection is `vec![0, 1]`, both `acc` and `v` equal 0, so error occurred.

It seems that code like this is correct,

```rust
let _ = projection.iter().fold(0, |mut acc, v| {
    if !(acc == 0 && *v == 0) {
        assert!( 
            *v > acc, 
            "The projection on IPC must be ordered and non-overlapping" 
        ); 
    }
    acc = *v;
    acc
});
```

Can I create the PR?

**Comment by jorgecarleitao** [comment]
Hey! Thanks for the report. Sure, shoot it and I will give it a review :)

**Comment by Dandandan** [comment]
What about changing the initial `acc` to `-1` ;)?

Even better / idiomatic would be to use `windows(2)` over the slice.

**Comment by illumination-k** [comment]
Thanks for your kind comments. I open the pr according to the comments!
