### ISSUE TITLE
Convenience methods on StructArray

### ISSUE THREAD

**Issue by abreis** [jorgecarleitao/arrow2#61]
`StructArray` in arrow-rs has a few convenience methods that `StructArray` in arrow2 is missing:
```rust
/// Returns the field at pos. 
fn column(&self, pos: usize) -> &ArrayRef;

/// Return the number of fields in this struct array. 
fn num_columns(&self) -> usize;

/// Returns the fields of the struct array. 
fn columns(&self) -> Vec<&ArrayRef>;

/// Returns child array refs of the struct array. 
fn columns_ref(&self) -> Vec<ArrayRef>;

/// Return field names in this struct array.
fn column_names(&self) -> Vec<&str>;

/// Return child array whose field name equals to column_name. 
fn column_by_name(&self, column_name: &str) -> Option<&ArrayRef>;
```

For reference, arrow2::StructArray has:
```rust
fn values(&self) -> &[Arc<dyn Array>]; // technically the same as `columns()`
fn fields(&self) -> &[Field];
```
which is enough to replicate those methods. Having them available on StructArray is quite convenient though, particularly for new users.

Is it okay if I submit a PR to bring most of them back?  
(and I'm thinking of making the return types more idiomatic, but that can be discussed in the PR)

**Comment by jorgecarleitao** [comment]
Thanks @abreis ! Agree (also with idiomatic). Fire it away!
