### ISSUE TITLE
Cannot use Snappy decompression

### ISSUE THREAD

**Issue by mdrach** [jorgecarleitao/arrow2#626]
Apologies if this is a silly question; if so point me to the docs that have the answer.  I'm trying to run the example that reads a parquet file with snappy decompression.  I get the following error.

```
Error: External("", General("Compression Snappy is not installed"))
```

I'm on OSX 11.6.1 and I've installed [snappy](https://stackoverflow.com/questions/22794807/installing-avro-in-mac-os-x) though I'm not sure this is even necessary given that parquet2 uses [snap](https://crates.io/crates/snap).  

I've attached a minimal project that produces this error: [test_parquet_snappy.zip](https://github.com/jorgecarleitao/arrow2/files/7585727/test_parquet_snappy.zip)

Any pointers here?  Thanks.

**Comment by jorgecarleitao** [comment]
Hi, you need to use the feature `io_parquet_compression` - essentially we offer the possibility to not drag dependencies if the user does not want them and these are some of them. Note that you do not need snappy installed on your machine.

**Comment by houqp** [comment]
Perhaps the error message could be more actionable? Like something along the lines of `Feature compression Snappy is not enabled`

**Comment by jorgecarleitao** [comment]
I agree. This requires a small surgery to `parquet2`: https://github.com/jorgecarleitao/parquet2/pull/69 so that we can match the error and propagate it to our end.

**Comment by jorgecarleitao** [comment]
Ok, there is now a PR to fix this :)
