### ISSUE TITLE
Add `lower` and `upper` support for string

### ISSUE THREAD

**Issue by Xuanwo** [jorgecarleitao/arrow2#635]
Hello, do you have a plan to support `compute::lower::lower` and `compute::upper::upper`?

If it's OK, I will start a PR to implement those two functions.

> They are required by https://github.com/datafuselabs/databend/issues/3013 and https://github.com/datafuselabs/databend/issues/3010

**Comment by jorgecarleitao** [comment]
Yeap, in scope indeed. 👍

Hint: there is a cool optimization on them

**Comment by Xuanwo** [comment]
> Hint: there is a cool optimization on them

Wow, sounds interesting. How about giving me some more detailed tips?
