### ISSUE TITLE
Consider support u128 for PrimitiveArray ?

### ISSUE THREAD

**Issue by yjhmelody** [jorgecarleitao/arrow2#639]

**Comment by jorgecarleitao** [comment]
Thanks!

This would be outside of the arrow specification. Since this crate follows Arrow's specification, such addition would need to be approved in Apache Arrow's official channels.

Maybe a starting point would be to describe the use-case: is the idea to have a larger unsigned for compute?

**Comment by yjhmelody** [comment]
Ok, I closed it,
