### ISSUE TITLE
Consider change compute signatures to use Scalar API

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/arrow2#659]
We currently have two different signatures in the compute API for scalars:

* `op_scalar(lhs: &PrimitiveArray<T>, rhs: &T) -> PrimitiveArray<T>`
* `op_scalar(lhs: &PrimitiveArray<T>, rhs: &PrimitiveScalar<T>) -> PrimitiveArray<T>`

I think that it is a bit confusing. What others think about changing all to the latter option?

The reason for the latter is that some operations require the logical type of the `rhs`, notably when adding a timestamp with a duration (i64 representing s, ms, us or ns encapsultated in the logical type).

We already have an API to support these operations against pure `T`, e.g. `unary(lhs, |x| x + *rhs)` for addition, in case the user wants to physical op.

**Comment by yjhmelody** [comment]
maybe
```rust
op_scalar<T>(lhs: &PrimitiveArray<T>, rhs: impl Into<PrimitiveScalar<T>>) -> PrimitiveArray<T>
```
Or define a new trait for the basic type cast situations?

If my idea is bad, please ignore it.

**Comment by jorgecarleitao** [comment]
That is an awesome idea!

**Comment by jorgecarleitao** [comment]
I tried this but I am struggling with the implementation:

```rust
fn f<T: NativeType, I: Into<PrimitiveScalar<T>>>(a: &PrimitiveArray<T>, b: &I) -> {
    let b = b.into(); // can't be done because it is a reference, not a value
}
```

any ideas?

**Comment by houqp** [comment]
how about ` AsRef<PrimitiveScalar<T>>`?

**Comment by Jimexist** [comment]
@jorgecarleitao is this issue still open?

**Comment by jorgecarleitao** [comment]
atm I am fine with the API we have - when a scalar is really needed (`dyn` or logical type) we use it, else we do not. I think we need more data points from downstream dependencies, to see how the API feels for others.
