### ISSUE TITLE
 reading of parquet binary type, is very slow:

### ISSUE THREAD

**Issue by ldn9638** [jorgecarleitao/arrow2#666]
I find [ https://github.com/jorgecarleitao/arrow2/blob/main/src/io/parquet/read/binary/mod.rs#L34]
capacity cannot be pre allocated here，Cause ‘extend_from_Slice’ is very slow。
![image](https://user-images.githubusercontent.com/92718695/145190503-00f2a24d-13af-4852-9e3c-d59752c19574.png)

**Comment by jorgecarleitao** [comment]
Ahahaha I also found that out yesterday! Fully agree, we should pre-reserve this one for sure. Not that in plain, a value is always [4 bytes][values] and each page anounces how many values it contains, so we can pre-allocate exactly.
