### ISSUE TITLE
Arrow2 cannnot open arrow IPC files written by Julia's Arrow.jl, `Unable to get dictionaries from footer`.

### ISSUE THREAD

**Issue by pcjentsch** [jorgecarleitao/arrow2#677]
Arrow2 has trouble opening IPC files written by `Arrow.jl` in Julia. I think it's an issue on this side because `pyarrow` is able to open the files. 

I have created [a git repository](https://github.com/pcjentsch/testing_ipc) with a sample IPC file written by Arrow.jl and some sample code from Arrow2 that reproduces the error by trying to read the IPC file. 

Thank you for the great package! Let me know if there is any other way I can help, and of course if this error might be on Julia's side.

**Comment by jorgecarleitao** [comment]
Thanks a lot for the investigation. This is indeed a bug on our side where we are being too restrictive in what we accept. PR to fix it in #678

```bash
cargo run --features io_ipc,io_print --example ipc_file_read "test.ipc"
```

```bash
+----------------------+------+
| a                    | b    |
+----------------------+------+
| 0.23161250793669264  | test |
| 0.7067493353734342   | test |
| 0.9173674364326969   | test |
...
```

> Thank you for the great package! 

Thank you 🙇
