### ISSUE TITLE
Fix LIKE escape issues

### ISSUE THREAD

**Issue by Dandandan** [jorgecarleitao/arrow2#702]
Due to using `regex` crate directly, it's sensitive to not escape `like` patterns`.
A solution to it can be using the `escape` function in `regex`: https://docs.rs/regex/1.5.4/regex/fn.escape.html

Next, there should be a possibility to escape the `%` and `_` characters.

Arrow-rs issues/PRs:

https://github.com/apache/arrow-rs/pull/1085
https://github.com/apache/arrow-rs/pull/1042
https://github.com/apache/arrow-rs/issues/415

**Comment by jorgecarleitao** [comment]
I struggle a bit to implement this because the rules are quite specific to the particular dialect. E.g. databend uses Mysql, Datafusion uses postgres, Polars uses python's regex.

Is there an escape that covers them all? Any ideas how we accommodate these differences, @Dandandan @houqp @ritchie46 @sundy-li ?

**Comment by Dandandan** [comment]
I think it's best to split this into two:

* (Bug) not escaping regex patterns like `.*` `.`, parentheses, etc. That should be easy as the regex crate offers the `escape` method.
* (Feature) supporting escaping `%` and `_`, e.g. with something like `\%` and `\_`, or making it configurable.

**Comment by sundy-li** [comment]
`databend`  built regexp pattern by like pattern using escape.
 https://github.com/datafuselabs/databend/blob/44bab57d297c0f05440014a5270318bdb4485d8e/common/datavalues/src/arrays/ops/like.rs
 
Maybe we can introduce LIKE_OPTIONS to cover possible dialects in arrow2.

**Comment by jorgecarleitao** [comment]
Really sorry for the late reply! :(

Those makes a lot of sense.

**Comment by daniel-martinez-maqueda-sap** [comment]
No worries. Here's the PR: https://github.com/apache/arrow-rs/pull/2258 :)
