### ISSUE TITLE
Why vec![] works faster?

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#714]
Benchmark [Codes](https://gist.github.com/sundy-li/346258710ce1af1f8391f7718cd6321c)

```
fn abs_d(array: &PrimitiveArray<i32>) -> PrimitiveArray<u32> {
    let it = array.values().iter().map(|x| x.abs() as u32);
    unsafe { PrimitiveArray::<u32>::from_trusted_len_values_iter_unchecked(it) }
}

fn abs_v(array: &PrimitiveArray<i32>) -> PrimitiveArray<u32> {
    let mut data = vec![0u32; array.len()];
    array.values().iter().enumerate().for_each(|(i, x)| {
        data[i] = x.abs() as u32;
    });

    PrimitiveArray::<u32>::from_vec(data)
}

fn abs_e(array: &PrimitiveArray<i32>) -> PrimitiveArray<u32> {
    let mut data = Vec::with_capacity(array.len());
    unsafe { data.set_len(array.len()) }
    array.values().iter().enumerate().for_each(|(i, x)| {
        data[i] = x.abs() as u32;
    });

    PrimitiveArray::<u32>::from_vec(data)
}
```
Results:

```
Gnuplot not found, using plotters backend
abs_d                   time:   [318.68 us 320.62 us 322.84 us]                  

abs_v                   time:   [217.97 us 219.60 us 221.25 us]                

abs_e                   time:   [318.71 us 321.41 us 324.39 us]                  

```

**Comment by sundy-li** [comment]
Why did this benchmark?

Let's see this function

https://github.com/jorgecarleitao/arrow2/blob/3c10b1669d0a55d78824d505f02ad86952b193ba/src/compute/cast/binary_to.rs#L51-L59

As you can see the `iter` is an iterator of  `Option<T>`, so it'll cause much prediction miss when collecting iter into Array.
I think we can avoid this performance drop by using bit skills.


Example of [velox's function](https://facebookincubator.github.io/velox/develop/scalar-functions.html):

```
template <typename T>
VELOX_UDF_BEGIN(ceil)
FOLLY_ALWAYS_INLINE bool call(T& result, const T& a) {
  result = std::ceil(a);
  return true;
}
VELOX_UDF_END();
```

As you can see this small function returns a bool. So there will no prediction-miss to building another array.


```
let dest_array = IntArray::new(vec![0; rows] );
let bitmap = Bitmap::new(rows);
dest_array.iter_mut().zip(source_array.iter()).for_each( |a,  b|  {
   bitmap.add(call(a, b));
}  )
```

**Comment by ritchie46** [comment]
I don't really understand? In the benchmark you write you collect with `from_trusted_len_values_iter_unchecked`. There is no bitmap involved there.

**Comment by sundy-li** [comment]
> I don't really understand? In the benchmark you write you collect with from_trusted_len_values_iter_unchecked. There is no bitmap involved there.

Yes, the benchmark example ignores  all bitmap, just to show why `vec![]` works faster than others.

The second example is to improve performance in transforming array.

**Comment by ritchie46** [comment]
But why is is vec faster in that first case? Autovectorization?

**Comment by sundy-li** [comment]
Asked in https://users.rust-lang.org/t/why-vec-works-faster-than-others/69435

**Comment by jorgecarleitao** [comment]
This is indeed unexpected. I think that the thread in users.rust-lang is more fitting, as this is a std-specific issue (with Vec)

**Comment by sundy-li** [comment]
According to the discussions in the users group, maybe it's related to a different arch, let's close it.
