### ISSUE TITLE
COW from  Array into MutableArray

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#741]
https://doc.rust-lang.org/std/borrow/enum.Cow.html
https://doc.rust-lang.org/std/sync/struct.Arc.html#method.make_mut

**Comment by jorgecarleitao** [comment]
This is a very neat idea. I will mark it as investigation as I am not sure about its implications, but it is definitely something we should explore!

**Comment by sundy-li** [comment]
Refer COW in ClickHouse:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/COW.h

**Comment by ritchie46** [comment]
Wow.. this is interesting.

**Comment by jorgecarleitao** [comment]
@sundy-li , would you consider this to be done? #794 seems to be exactly what this is about, right?
