### ISSUE TITLE
ser/de for datatype within scope?

### ISSUE THREAD

**Issue by houqp** [jorgecarleitao/arrow2#766]
I noticed `Serialize, Deserialize` are not derived for `datatypes::DataType` while working on the roapi port. Is this within scope of arrow2? or should we come up with our own custom implementations downstream instead?

**Comment by ritchie46** [comment]
If it does, I think it should be feature flagged as it brings the serde dependency with it.

**Comment by houqp** [comment]
I agree, should definitely be feature gated if we are to add it to the core.

**Comment by jorgecarleitao** [comment]
I think we should under a gate - serde is so ubiquitous in Rust, and it is such a pain to implement it to a foreign struct xD
