### ISSUE TITLE
Add support for ODBC

### ISSUE THREAD

**Issue by jorgecarleitao** [jorgecarleitao/arrow2#829]
@pacman82 wrote this amazing library https://github.com/pacman82/odbc-api that we should consider depending on for reading and writing from/to ODBC.

imo ODBC is quite central in data, which is why imo I think "this must live".

Question: should this live in arrow2 as optional (e.g. `src/io/odbc/`) or somewhere else?

Any thoughts @ritchie46 , @houqp , @pacman82, @sundy-li , @Dandandan?

**Comment by pacman82** [comment]
Hi thanks @jorgecarleitao for promoting my library. I think the maintainers of this library a probably qualified best to decide wether or not an optional dependency is suitable here. I think the most important impact of this decision is wether or not we want the ODBC glue code to to share a CI and release cycle with the rest of `arrow2odbc`.

I am happy to help out either way.

**Comment by pacman82** [comment]
Well, at least my naming scheme would not do well for an individual crate. `arrow22odbc` is just silly 😅 .

**Comment by pacman82** [comment]
Just realized that I already renamed `arrow2odbc` into `arrow-odbc`. Seeing that now an `arrow2` exists, I am really happy about doing that.

**Comment by ritchie46** [comment]
I do think there is some benefit in maintaining the dependency optionally in arrow2. I have heard several cases of users who use connector-x + polars rust don't realize that both should point to exactly the same arrow version to work. It is very easy to get out of sync unless we make sure that we distribute such a dependency through arrow.

**Comment by jorgecarleitao** [comment]
I agree that sticking to one driver is a good idea.

Could we run them on docker, or you think it is an even worse requirement? Asking because it would also make it easier to boot the db

**Comment by pacman82** [comment]
It is very easy to operate on CI. Here is how I spin up the DB to test the `odbc2parquet` tool.

<https://github.com/pacman82/odbc2parquet/blob/eab372a9ad50ea065b461e41ee6e26d9fbc71097/.github/workflows/test.yml#L1>

**Comment by jorgecarleitao** [comment]
Closed by #849
