### ISSUE TITLE
Writing to Parquet fails for extension types that contain lists

### ISSUE THREAD

**Issue by dexterduck** [jorgecarleitao/arrow2#830]
If you create an extension type that wraps any kind of list type,  conversion to Parquet format fails. 
As far as I can tell, this could be fixed by updating  the `nested_array_to_page` function in `io/parquet/write/mod.rs` to use:
```rust
match array.data_type().to_logical_type() {
```
instead of 
```rust
match array.data_type() {
```

**Comment by BlackSmith96** [comment]
I'm happy to do this.  Can you assign this issue to me?
