### ISSUE TITLE
Unable to decode parquet file with List[PrimitiveArray<f64>]

### ISSUE THREAD

**Issue by Igosuki** [jorgecarleitao/arrow2#890]
Reading the following file : https://github.com/Igosuki/arrow2/blob/parquet_file_fail/part-00000-ff6ed8b4-84b9-4d58-b491-6c6401ba8925-c000.snappy.parquet
Fails with :
```
NotYetImplemented(Decoding 'PlainDictionary'-encoded optional any pages is not yet implemented for Primitive)
```

It can be read by arrow-rs

Any idea why the decoding fails here ?

**Comment by jorgecarleitao** [comment]
Thanks for reporting it.

#892 fixes this one, but does not fixes reading this file. I am marking this as a blocker for 0.10 - we need to correctly read multi-page nested columns.

**Comment by Igosuki** [comment]
👍☺️
