### ISSUE TITLE
Parquet: Snappy buffer size limitation. 

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#932]
Writing large parquet files can lead to:

```
ArrowError(ExternalFormat("External format error: underlying snap error: snappy: input buffer (size = 68397383472) is larger than allowed (size = **4294967295)**
```

I believe we already discussed this earlier in a polars issue, but I cannot reproduce it. I open this issue to explore ways to circumvent it. 
I assume we can prevent this by passing smaller `Chunks` to the writer?

Is there a way upfront to estimate the size of a buffer that will be send to snappy?

**Comment by jorgecarleitao** [comment]
We need to support splitting the arrays in multiple parquet pages when writing, since each page is compressed independently

**Comment by jorgecarleitao** [comment]
Alternatively, split the chunk in smaller parts ^^
