### ISSUE TITLE
Support datetimes with timezone offsets like +01:00

### ISSUE THREAD

**Issue by glennpierce** [jorgecarleitao/arrow2#936]
When trying to convert a pandas_df into a polars one I get

`exceptions.ArrowErrorException: OutOfSpec("The datatype \"tsu:+01:00\" is still not supported in Rust implementation")`

How involved is it to add this support ?

**Comment by jorgecarleitao** [comment]
we support `+01:00` but not `tsu:+01:00` as per arrow spec: https://github.com/apache/arrow/blob/master/format/Schema.fbs#L341

What Python datetime are you using for it to be represented as `tsu:+01:00`?

**Comment by glennpierce** [comment]
> we support `+01:00` but not `tsu:+01:00` as per arrow spec: https://github.com/apache/arrow/blob/master/format/Schema.fbs#L341
> 
> What Python datetime are you using for it to be represented as `tsu:+01:00`?

I was reading a pandas dataframe from my db then converting it with polars when I got that errer.

ie 

```
pandas_df = pd.read_sql(value_query, con=conn)
df = pl.from_pandas(pandas_df)
```

The pandas dataframe was like

```
[1437 rows x 3 columns]
                                   ts  sensor_id  value
0    2019-06-14 00:00:00.944000+00:00     611282   48.0
1    2019-06-14 00:01:00.814000+00:00     611282   48.0
2    2019-06-14 00:02:02.028000+00:00     611282   48.0
3    2019-06-14 00:03:01.102000+00:00     611282   48.0
4    2019-06-14 00:04:02.014000+00:00     611282   48.0
```

**Comment by jorgecarleitao** [comment]
strange - why does pandas map `+00:00` to `tsu:+01:00`?

**Comment by glennpierce** [comment]
That's just a partial part of the dataframe. I assume the issue is when the uk clocks changed of 29th of march I think.

**Comment by jorgecarleitao** [comment]
But shouldnt that be represented simply as "London/Berlin"? The representation +01:00 is a fixed offset, which does not take day light saving changes into account (right?)

**Comment by glennpierce** [comment]
This is odd I just made a test case and can't replicate it now. Will close the issue for now.
