### ISSUE TITLE
Parquet regression: `exceptions.ArrowErrorException: NotYetImplemented("Can't read Dictionary(UInt32, LargeUtf8, false) from parquet")`

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#955]
CI round trips fail on writing/reading dictionary arrays with keys `UInt32` and values `LargeUtf8`.

**Comment by jorgecarleitao** [comment]
The issue is that we do not have statistics structs for dictionary arrays - the dictionary is read, but the statistics are not.

**Comment by ritchie46** [comment]
So I trigger that error when reading statistics? I need to check the error type and ignore the statistic on this error type? 

Or should I check the schema first and if any dict in there don't try to parse statistics?

**Comment by ritchie46** [comment]
What did we do before this? Just not include the dictionary column in the statistics?

**Comment by jorgecarleitao** [comment]
I am working on this - the statistics API is clumsy (we should just have stats as arrays, not individual values), I will just fix this together with the API

**Comment by ritchie46** [comment]
All right. I'll wait a bit. :)

**Comment by ritchie46** [comment]
Fixed. Confirmed by the CI run in https://github.com/pola-rs/polars/pull/3181
