### ISSUE TITLE
Add documentation to guide

### ISSUE THREAD

**Issue by elferherrera** [jorgecarleitao/arrow2#96]
I am considering moving some of the pages I have in the arrow guide I was writing to the guide Arrow2 has.

what do you think?

**Comment by jorgecarleitao** [comment]
❤️

**Comment by elferherrera** [comment]
Cool, I'm glad you support the idea. Let me start moving the pages here

**Comment by jorgecarleitao** [comment]
I for one really enjoyed reading the guide that you wrote ^_^

**Comment by jorgecarleitao** [comment]
I think that we closed this recently, right?

**Comment by elferherrera** [comment]
I think you can close it. I added a page from the old guide but the rest of the pages dont apply since ArrayData is gone and the new constructors are very different
