### ISSUE TITLE
FileWriter could call self.start() for the user

### ISSUE THREAD

**Issue by TurnOfACard** [jorgecarleitao/arrow2#980]
When writing a file using a `FileWriter` in arrow2, the user must always call start(). As it appears that this only writes the magic bytes 'PAR1', this could be written before `FileWriter::try_new()` returns.

If the change is acceptable, I'll write a PR.

https://github.com/jorgecarleitao/arrow2/blob/2d70fbf46fd37f4ef532945c588be69a71998e44/src/io/parquet/write/file.rs#L55-L78

**Comment by TurnOfACard** [comment]
That makes sense.

An alternative is during the first write of a row group (IO bounded), instead of throwing an error, write the magic bytes:

https://github.com/jorgecarleitao/parquet2/blob/47edd88ab831da74c5e17d7b0e483ddc243f0f6a/src/write/file.rs#L98-L107

That removes a potential runtime error?

**Comment by jorgecarleitao** [comment]
I agree! - we have something like that in IPC file writer, for inspiration :)

**Comment by jorgecarleitao** [comment]
This is now fixed and released. Thanks a lot, @TurnOfACard for the report!
