### ISSUE TITLE
Async S3 write support ?

### ISSUE THREAD

**Issue by sundeepks** [jorgecarleitao/arrow2#995]
Hey, do we have support / examples for writing s3 files ?

**Comment by jorgecarleitao** [comment]
Hey, thanks for your interest! which s3 binding / library are you using?

In general it is optimal to use `async` to interact with s3. Thus, you need a struct that implements `AsyncWrite + Unpin + Send` (the s3 lib should provide that) and use it on the example of writing to a `FileSink` here:

https://docs.rs/arrow2/latest/arrow2/io/parquet/write/struct.FileSink.html#examples

Does it make sense?

**Comment by sundeepks** [comment]
thanks a lot for your response, was able to write the parquet file in s3 using the above.
