### ISSUE TITLE
Replace `fn Offset::is_large()` with `const Offset::IS_LARGE`. 

### ISSUE THREAD

**Issue by HaoYang670** [jorgecarleitao/arrow2#999]
Just as what we have done in arrow-rs: https://github.com/apache/arrow-rs/pull/1664, we can use `const` to represent `offset::is_large`:
```rust
pub trait Offset: super::private::Sealed + Index {
    /// Whether it is `i32` (false) or `i64` (true).
    const IS_LARGE: bool;
}

impl Offset for i32 {
    const IS_LARGE: bool = false;
}

impl Offset for i64 {
    const IS_LARGE: bool = true;
}

**Comment by HaoYang670** [comment]
@jorgecarleitao Do we need this change? Or inline function is good enough?

**Comment by jorgecarleitao** [comment]
Thanks @HaoYang670! It is a constant, so I agree that it is better represented as a `const` 👍

**Comment by HaoYang670** [comment]
I will file a PR this weekend. It is my pleasure to contribute to Arrow2 !!

**Comment by jorgecarleitao** [comment]
Awesome, thanks a lot 🙇
